spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simplebank
    username: simplebankuser
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /simplebank
